-- Adminer 5.2.1 PostgreSQL 17.4 dump

DROP TABLE IF EXISTS "articles";
CREATE TABLE "public"."articles" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "author" character varying(100) NOT NULL,
    "content" text,
    "publication_date" timestamp(6) NOT NULL,
    "title" character varying(255) NOT NULL,
    CONSTRAINT "articles_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "articles" ("id", "author", "content", "publication_date", "title") VALUES
(1,	'Joel Romaric',	'Ce livre parle de la science des habitudes ...',	'2025-05-30 12:46:24.290792',	'Le pouvoir de l''habitude'),
(3,	'L''éclaireur',	'Le paysage médiatique camerounais est secoué depuis quelques semaines par l''article 15 de la constitution qui stipule que tout mandat impératif est nul ...',	'2025-05-30 13:26:33.242401',	'Le mandat impératif'),
(2,	'Folepap victor',	'La célébration de la fête nationale de l''unité dans la localité de Toumaka ...',	'2025-05-30 13:13:00.243289',	'Les festivités du 20 Mai en campagne'),
(5,	'Nzui la panthère',	'Braquage spectaculaire dans la capitale ...',	'2025-05-30 13:37:25.077755',	'Faits divers');

DROP TABLE IF EXISTS "comments";
CREATE TABLE "public"."comments" (
    "id" bigint DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "author" character varying(100) NOT NULL,
    "comment_date" timestamp(6) NOT NULL,
    "content" text NOT NULL,
    "article_id" bigint NOT NULL,
    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "comments" ("id", "author", "comment_date", "content", "article_id") VALUES
(1,	'Alice',	'2025-05-30 12:50:54.979221',	'Excellent article! Merci.',	1),
(2,	'Romaric',	'2025-05-30 13:14:10.271546',	'Super interessant!',	2),
(4,	'Lopeze',	'2025-05-30 13:23:50.907974',	'Toumaka, mon beau village',	2),
(5,	'titi',	'2025-05-30 13:38:41.403114',	'Vendons le pays ci',	5);

ALTER TABLE ONLY "public"."comments" ADD CONSTRAINT "fkk4ib6syde10dalk7r7xdl0m5p" FOREIGN KEY (article_id) REFERENCES articles(id) NOT DEFERRABLE;

-- 2025-05-30 13:05:52 UTC
